version: '3.2'

services:
  adlist-merger:
    container_name: Adlist-Merger
    build: .
    restart: "unless-stopped"
    volumes:
      - ./appdata:/usr/src/appdata
      - ./git_folder:/usr/src/git_folder